server:
  port: 8080

spring:
  config:
    activate:
      on-profile: default
  application:
    name: bookings
  datasource:
    url: jdbc:mysql://${bookings-db:localhost}:3306/bookings-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

app:
  environment:
    flights-host: ${flights-host:localhost}
    hotels-host: ${hotels-host:localhost}

--- # Testing configuration

server:
  port: ${random.int(5000,5100)}

spring:
  config:
    activate:
      on-profile: test
  application:
    name: bookings
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: pablo
    password: pablo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  environment:
    bookings-host: none
