server:
  port: 8081

spring:
  config:
    activate:
      on-profile: default
  application:
    name: flights
  datasource:
    url: jdbc:mysql://${flights-db:localhost}:3306/flights-db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update



--- # Testing configuration

server:
  port: ${random.int(5000,5100)}

spring:
  config:
    activate:
      on-profile: test
  application:
    name: flights
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: pablo
    password: pablo
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  environment:
    flights-host: none
